import sys

src = r'c:\Users\jay\Downloads\tso_client-1.5.8.6\tso_client-1.5.8.6\userscripts\user_geo_manager.js'

with open(src, 'rb') as f:
    content = f.read()

old = (
    b'    // ------ Depleted Mines ------\r\n'
    b'    var allDepMines = (data.depletedMines || []).slice();\r\n'
    b'    allDepMines.sort(function (a, b) { return a.Name.localeCompare(b.Name); });\r\n'
    b'    var depMines     = allDepMines.filter(function (m) { return !_gmOreLimit[m.OreName]; });\r\n'
    b'    var limitedMines = allDepMines.filter(function (m) { return  _gmOreLimit[m.OreName]; });\r\n'
    b'\r\n'
    b'    out += \'<div class="gm-section">Depleted Mines (\' + depMines.length + \')</div>\';\r\n'
    b'    if (depMines.length > 0) {\r\n'
    b'        var sendAllBtn = $(\'<button>\').attr({\r\n'
    b'            id: \'gmDepSendAllBtn\',\r\n'
    b'            \'class\': \'btn btn-xs btn-success\'\r\n'
    b'        }).text(\'Send All\').prop(\'outerHTML\');\r\n'
    b'        out += createTableRow([[3, \'Mine\'], [3, \'Ore\'], [2, \'Best Geo\'], [2, sendAllBtn], [2, \'\']], true);\r\n'
    b'        depMines.forEach(function (m) {\r\n'
    b'            var searching   = data.searchingByOre[m.OreName] || 0;\r\n'
    b'            var deplCount   = data.depletedCountByOre[m.OreName] || 1;\r\n'
    b'            var atCap       = searching >= deplCount;\r\n'
    b'            var best        = _gmBestGeo(data.geos, m.OreName, []);\r\n'
    b'            var bestLabel, sendBtn;\r\n'
    b'            if (atCap) {\r\n'
    b'                bestLabel = \'<span style="color:#ffaa00">\' + searching + \' geo(s) searching</span>\';\r\n'
    b'                sendBtn   = \'<span style="color:#999;font-style:italic;">At cap</span>\';\r\n'
    b'            } else {\r\n'
    b'                bestLabel = best\r\n'
    b'                    ? (best.IsIdle ? best.Name : \'<em>\' + best.Name + \' (busy)</em>\')\r\n'
    b'                    : \'<span style="color:#999">none</span>\';\r\n'
    b'                sendBtn = (best && best.IsIdle)\r\n'
    b'                    ? $(\'<button>\').attr({\r\n'
    b'                        \'class\'   : \'btn btn-xs btn-success gmDepSendBtn\',\r\n'
    b'                        \'data-ore\': m.OreName\r\n'
    b'                      }).text(\'Send Geo\').prop(\'outerHTML\')\r\n'
    b'                    : \'\';\r\n'
    b'            }\r\n'
    b'            var markBtn = $(\'<button>\').attr({\r\n'
    b'                \'class\'   : \'btn btn-xs btn-default gmMarkLimitBtn\',\r\n'
    b'                \'data-ore\': m.OreName\r\n'
    b'            }).text(\'At Limit\').prop(\'outerHTML\');\r\n'
    b'            var gotoIcon = getImageTag(\'accuracy.png\', \'18px\', \'18px\')\r\n'
    b'                .replace(\'<img\', \'<img id="gmGoto_\' + m.Grid + \'"\')\r\n'
    b'                .replace(\'style="\', \'style="cursor:pointer;vertical-align:middle;\');\r\n'
    b'            out += createTableRow([\r\n'
    b'                [3, gotoIcon + \'&nbsp;\' + m.Name],\r\n'
    b'                [3, getImageTag(m.OreName, \'18px\') + \'&nbsp;\' + loca.GetText(\'RES\', m.OreName)],\r\n'
    b'                [2, bestLabel],\r\n'
    b'                [2, sendBtn],\r\n'
    b'                [2, markBtn]\r\n'
    b'            ]);\r\n'
    b'        });\r\n'
    b'    } else {\r\n'
    b'        out += \'<div style="color:#999;padding:4px 10px;font-style:italic;">No depleted mines found.</div>\';\r\n'
    b'    }\r\n'
    b'\r\n'
    b'    // ------ At Game Limit section ------\r\n'
    b'    var limitedOres = Object.keys(_gmOreLimit);\r\n'
    b'    out += \'<div class="gm-section">At Game Limit (\' + limitedOres.length + \')</div>\';\r\n'
    b'    if (limitedOres.length > 0) {\r\n'
    b'        out += createTableRow([[3, \'Mine\'], [3, \'Ore\'], [2, \'Best Geo\'], [2, \'Send Anyway\'], [2, \'\']], true);\r\n'
    b'        var shownOres = {};\r\n'
    b'        limitedMines.forEach(function (m) {\r\n'
    b'            shownOres[m.OreName] = true;\r\n'
    b'            var best = _gmBestGeo(data.geos, m.OreName, []);\r\n'
    b'            var bestLabel = best\r\n'
    b'                ? (best.IsIdle ? best.Name : \'<em>\' + best.Name + \' (busy)</em>\')\r\n'
    b'                : \'<span style="color:#999">none</span>\';\r\n'
    b'            var sendBtn = (best && best.IsIdle)\r\n'
    b'                ? $(\'<button>\').attr({\r\n'
    b'                    \'class\'   : \'btn btn-xs btn-warning gmDepSendBtn\',\r\n'
    b'                    \'data-ore\': m.OreName\r\n'
    b'                  }).text(\'Send Anyway\').prop(\'outerHTML\')\r\n'
    b'                : \'<span style="color:#999">no idle geo</span>\';\r\n'
    b'            var clearBtn = $(\'<button>\').attr({\r\n'
    b'                \'class\'   : \'btn btn-xs btn-success gmClearLimitBtn\',\r\n'
    b'                \'data-ore\': m.OreName\r\n'
    b'            }).text(\'Clear Limit\').prop(\'outerHTML\');\r\n'
    b'            var gotoIcon = getImageTag(\'accuracy.png\', \'18px\', \'18px\')\r\n'
    b'                .replace(\'<img\', \'<img id="gmGoto_\' + m.Grid + \'"\')\r\n'
    b'                .replace(\'style="\', \'style="cursor:pointer;vertical-align:middle;\');\r\n'
    b'            out += createTableRow([\r\n'
    b'                [3, gotoIcon + \'&nbsp;\' + m.Name],\r\n'
    b'                [3, getImageTag(m.OreName, \'18px\') + \'&nbsp;\' + loca.GetText(\'RES\', m.OreName)],\r\n'
    b'                [2, bestLabel],\r\n'
    b'                [2, sendBtn],\r\n'
    b'                [2, clearBtn]\r\n'
    b'            ]);\r\n'
    b'        });\r\n'
    b'        limitedOres.forEach(function (ore) {\r\n'
    b'            if (shownOres[ore]) return;\r\n'
    b'            var best = _gmBestGeo(data.geos, ore, []);\r\n'
    b'            var bestLabel = best\r\n'
    b'                ? (best.IsIdle ? best.Name : \'<em>\' + best.Name + \' (busy)</em>\')\r\n'
    b'                : \'<span style="color:#999">none</span>\';\r\n'
    b'            var sendBtn = (best && best.IsIdle)\r\n'
    b'                ? $(\'<button>\').attr({\r\n'
    b'                    \'class\'   : \'btn btn-xs btn-warning gmDepSendBtn\',\r\n'
    b'                    \'data-ore\': ore\r\n'
    b'                  }).text(\'Send Anyway\').prop(\'outerHTML\')\r\n'
    b'                : \'<span style="color:#999">no idle geo</span>\';\r\n'
    b'            var clearBtn = $(\'<button>\').attr({\r\n'
    b'                \'class\'   : \'btn btn-xs btn-success gmClearLimitBtn\',\r\n'
    b'                \'data-ore\': ore\r\n'
    b'            }).text(\'Clear Limit\').prop(\'outerHTML\');\r\n'
    b'            out += createTableRow([\r\n'
    b'                [3, \'&mdash;\'],\r\n'
    b'                [3, getImageTag(ore, \'18px\') + \'&nbsp;\' + loca.GetText(\'RES\', ore)],\r\n'
    b'                [2, bestLabel],\r\n'
    b'                [2, sendBtn],\r\n'
    b'                [2, clearBtn]\r\n'
    b'            ]);\r\n'
    b'        });\r\n'
    b'    } else {\r\n'
    b'        out += \'<div style="color:#999;padding:4px 10px;font-style:italic;">No ores marked at game limit.</div>\';\r\n'
    b'    }\r\n'
)

new = (
    b'    // ------ Depleted Mines ------\r\n'
    b'    var allDepMines = (data.depletedMines || []).slice();\r\n'
    b'    allDepMines.sort(function (a, b) { return a.Name.localeCompare(b.Name); });\r\n'
    b'    var depMines = allDepMines;  // all depleted buildings shown here, including those at ore limit\r\n'
    b'\r\n'
    b'    out += \'<div class="gm-section">Depleted Mines (\' + depMines.length + \')</div>\';\r\n'
    b'    if (depMines.length > 0) {\r\n'
    b'        var sendAllBtn = $(\'<button>\').attr({\r\n'
    b'            id: \'gmDepSendAllBtn\',\r\n'
    b'            \'class\': \'btn btn-xs btn-success\'\r\n'
    b'        }).text(\'Send All\').prop(\'outerHTML\');\r\n'
    b'        out += createTableRow([[3, \'Mine\'], [3, \'Ore\'], [2, \'Best Geo\'], [2, sendAllBtn], [2, \'\']], true);\r\n'
    b'        depMines.forEach(function (m) {\r\n'
    b'            var searching   = data.searchingByOre[m.OreName] || 0;\r\n'
    b'            var deplCount   = data.depletedCountByOre[m.OreName] || 1;\r\n'
    b'            var atCap       = searching >= deplCount;\r\n'
    b'            var isLimited   = !!_gmOreLimit[m.OreName];\r\n'
    b'            var best        = _gmBestGeo(data.geos, m.OreName, []);\r\n'
    b'            var bestLabel, sendBtn, actionBtn;\r\n'
    b'\r\n'
    b'            // Soonest busy geo capable of searching this ore type\r\n'
    b'            var busyCapable = data.geos.filter(function(g) {\r\n'
    b'                try { return !g.IsIdle && _gmSearchMs(g.Spec, m.OreName) > 0; } catch(e) { return false; }\r\n'
    b'            });\r\n'
    b'            var soonestBusy = busyCapable.length > 0\r\n'
    b'                ? busyCapable.reduce(function(a, b) { return a.RemMs < b.RemMs ? a : b; })\r\n'
    b'                : null;\r\n'
    b'\r\n'
    b'            if (isLimited) {\r\n'
    b'                // Ore is at game limit: show soonest returning geo, "At limit" send label, Clear Limit button\r\n'
    b'                bestLabel = soonestBusy\r\n'
    b'                    ? \'<span style="color:#ffaa00">\' + soonestBusy.Name + \' ready in \' + _gmFmt(soonestBusy.RemMs) + \'</span>\'\r\n'
    b'                    : (best ? \'<em>\' + best.Name + \' (busy)</em>\' : \'<span style="color:#999">none</span>\');\r\n'
    b'                sendBtn   = \'<span style="color:#999;font-style:italic;">At limit</span>\';\r\n'
    b'                actionBtn = $(\'<button>\').attr({\r\n'
    b'                    \'class\'   : \'btn btn-xs btn-success gmClearLimitBtn\',\r\n'
    b'                    \'data-ore\': m.OreName\r\n'
    b'                }).text(\'Clear Limit\').prop(\'outerHTML\');\r\n'
    b'            } else if (atCap) {\r\n'
    b'                // Already enough geos searching: show soonest one returning\r\n'
    b'                var busyForOre = data.geos.filter(function(g) { return !g.IsIdle && g.BusyOre === m.OreName; });\r\n'
    b'                var soonestSearching = busyForOre.length > 0\r\n'
    b'                    ? busyForOre.reduce(function(a, b) { return a.RemMs < b.RemMs ? a : b; })\r\n'
    b'                    : null;\r\n'
    b'                bestLabel = soonestSearching\r\n'
    b'                    ? \'<span style="color:#ffaa00">\' + soonestSearching.Name + \' ready in \' + _gmFmt(soonestSearching.RemMs) + \'</span>\'\r\n'
    b'                    : \'<span style="color:#ffaa00">\' + searching + \' geo(s) searching</span>\';\r\n'
    b'                sendBtn   = \'<span style="color:#999;font-style:italic;">At cap</span>\';\r\n'
    b'                actionBtn = $(\'<button>\').attr({\r\n'
    b'                    \'class\'   : \'btn btn-xs btn-default gmMarkLimitBtn\',\r\n'
    b'                    \'data-ore\': m.OreName\r\n'
    b'                }).text(\'At Limit\').prop(\'outerHTML\');\r\n'
    b'            } else {\r\n'
    b'                // Normal: idle geo preferred, else show soonest busy geo that can search this ore\r\n'
    b'                if (best && best.IsIdle) {\r\n'
    b'                    bestLabel = best.Name;\r\n'
    b'                } else if (soonestBusy) {\r\n'
    b'                    bestLabel = \'<span style="color:#aaaaff">\' + soonestBusy.Name + \' ready in \' + _gmFmt(soonestBusy.RemMs) + \'</span>\';\r\n'
    b'                } else {\r\n'
    b'                    bestLabel = \'<span style="color:#999">none</span>\';\r\n'
    b'                }\r\n'
    b'                sendBtn = (best && best.IsIdle)\r\n'
    b'                    ? $(\'<button>\').attr({\r\n'
    b'                        \'class\'   : \'btn btn-xs btn-success gmDepSendBtn\',\r\n'
    b'                        \'data-ore\': m.OreName\r\n'
    b'                      }).text(\'Send Geo\').prop(\'outerHTML\')\r\n'
    b'                    : \'\';\r\n'
    b'                actionBtn = $(\'<button>\').attr({\r\n'
    b'                    \'class\'   : \'btn btn-xs btn-default gmMarkLimitBtn\',\r\n'
    b'                    \'data-ore\': m.OreName\r\n'
    b'                }).text(\'At Limit\').prop(\'outerHTML\');\r\n'
    b'            }\r\n'
    b'\r\n'
    b'            var gotoIcon = getImageTag(\'accuracy.png\', \'18px\', \'18px\')\r\n'
    b'                .replace(\'<img\', \'<img id="gmGoto_\' + m.Grid + \'"\')\r\n'
    b'                .replace(\'style="\', \'style="cursor:pointer;vertical-align:middle;\');\r\n'
    b'            out += createTableRow([\r\n'
    b'                [3, gotoIcon + \'&nbsp;\' + m.Name],\r\n'
    b'                [3, getImageTag(m.OreName, \'18px\') + \'&nbsp;\' + loca.GetText(\'RES\', m.OreName)],\r\n'
    b'                [2, bestLabel],\r\n'
    b'                [2, sendBtn],\r\n'
    b'                [2, actionBtn]\r\n'
    b'            ]);\r\n'
    b'        });\r\n'
    b'    } else {\r\n'
    b'        out += \'<div style="color:#999;padding:4px 10px;font-style:italic;">No depleted mines found.</div>\';\r\n'
    b'    }\r\n'
    b'\r\n'
    b'    // ------ At Game Limit section: one row per ore, no per-building rows ------\r\n'
    b'    var limitedOres = Object.keys(_gmOreLimit);\r\n'
    b'    out += \'<div class="gm-section">At Game Limit (\' + limitedOres.length + \')</div>\';\r\n'
    b'    if (limitedOres.length > 0) {\r\n'
    b'        out += createTableRow([[6, \'Ore\'], [2, \'Best Geo\'], [2, \'Send Anyway\'], [2, \'\']], true);\r\n'
    b'        limitedOres.forEach(function (ore) {\r\n'
    b'            var best = _gmBestGeo(data.geos, ore, []);\r\n'
    b'            var bestLabel = best\r\n'
    b'                ? (best.IsIdle ? best.Name : \'<em>\' + best.Name + \' (busy)</em>\')\r\n'
    b'                : \'<span style="color:#999">none</span>\';\r\n'
    b'            var sendBtn = (best && best.IsIdle)\r\n'
    b'                ? $(\'<button>\').attr({\r\n'
    b'                    \'class\'   : \'btn btn-xs btn-warning gmDepSendBtn\',\r\n'
    b'                    \'data-ore\': ore\r\n'
    b'                  }).text(\'Send Anyway\').prop(\'outerHTML\')\r\n'
    b'                : \'<span style="color:#999">no idle geo</span>\';\r\n'
    b'            var clearBtn = $(\'<button>\').attr({\r\n'
    b'                \'class\'   : \'btn btn-xs btn-success gmClearLimitBtn\',\r\n'
    b'                \'data-ore\': ore\r\n'
    b'            }).text(\'Clear Limit\').prop(\'outerHTML\');\r\n'
    b'            out += createTableRow([\r\n'
    b'                [6, getImageTag(ore, \'18px\') + \'&nbsp;\' + loca.GetText(\'RES\', ore)],\r\n'
    b'                [2, bestLabel],\r\n'
    b'                [2, sendBtn],\r\n'
    b'                [2, clearBtn]\r\n'
    b'            ]);\r\n'
    b'        });\r\n'
    b'    } else {\r\n'
    b'        out += \'<div style="color:#999;padding:4px 10px;font-style:italic;">No ores marked at game limit.</div>\';\r\n'
    b'    }\r\n'
)

count = content.count(old)
if count != 1:
    print('Pattern found %d times (expected 1)' % count)
    sys.exit(1)

content = content.replace(old, new, 1)
print('Patch applied OK')

with open(src, 'wb') as f:
    f.write(content)
print('Done.')
